---
title: "Quantitative component"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
require(tidyverse)
require(readxl)
require(patchwork)
require(ggthemes)
```

Oxygen (mol/m3) * 32 = Oxygen (mg/L)

```{r}
dorg<-read_excel("Quantitative component species list.xlsx", sheet="Organismal factors")%>%
  mutate(Include=replace_na(Include, TRUE))%>%
  filter(Include)%>%
  rename(Specific_location=Climate_location)

dclim<-read_excel("Quantitative component species list.xlsx", sheet="Climate factors")%>%
  mutate(Temperature_Extreme=Temperature+Temperature_SD,
         pH_Extreme=pH-pH_SD,
         Salinity_Extreme=Salinity-Salinity_SD,
         Oxygen=Oxygen_molm3*32,
         Oxygen_Extreme=(Oxygen_molm3-Oxygen_molm3_SD)*32)%>%
  select(-Salinity_SD, -Temperature_SD, -pH_SD, -Oxygen_molm3, -Oxygen_molm3_SD)%>%
  gather(-Region, -Specific_location, key="Climate_parameter", value="Climate_expected2096")%>%
  separate(Climate_parameter, into=c("Climate_parameter", "Intensity"), sep="_", fill="right")%>%
  mutate(Intensity=replace_na(Intensity, "Mean"))%>%
  drop_na()

d<-dorg%>%
  left_join(dclim, by=c("Climate_parameter", "Specific_location"))

dsum<-d%>%
  #Divide growth by days to get growth rate
  mutate(Organismal_treatment=if_else(Organismal_parameter=="Growth", Organismal_treatment/Exposure_days, Organismal_treatment),
         Organismal_control=if_else(Organismal_parameter=="Growth", Organismal_control/Exposure_days, Organismal_control),
         Organismal_treatment=if_else(Organismal_parameter=="Mortality rate", 100-(1-exp(Organismal_treatment))*100, Organismal_treatment),
         Organismal_control=if_else(Organismal_parameter=="Mortality rate", 100-(1-exp(Organismal_control))*100, Organismal_control))%>%
  mutate(Organismal_parameter=recode(Organismal_parameter, `Mortality rate`="Survival"))%>%
  #Calculate instantaneous mortality/abnormal development rates 
  mutate(Organismal_treatment=if_else(Organismal_parameter%in%c("Survival", "Development") & Organismal_treatment==100, 99.99, Organismal_treatment),
         Organismal_control=if_else(Organismal_parameter%in%c("Survival", "Development") & Organismal_control==100, 99.99, Organismal_control))%>%
  mutate(Organismal_treatment=if_else(Organismal_parameter%in%c("Survival", "Development"), log((100-Organismal_treatment)/100)/Exposure_days, Organismal_treatment),
         Organismal_control=if_else(Organismal_parameter%in%c("Survival", "Development"), log((100-Organismal_control)/100)/Exposure_days, Organismal_control))%>%
  mutate(Organismal_parameter=recode(Organismal_parameter, Growth="Growth rate"))%>%
  mutate(Climate_conversion=(Climate_expected2096-Climate_control)/(Climate_treatment-Climate_control), #Create factor to convert experimental range to expected change by applying (expected change)/(measured change)
         Organismal_expected2096=((Organismal_treatment-Organismal_control)/Organismal_control)*Climate_conversion)%>% #Calculate rough effect size as (difference in organismal parameter)/(control organismal parameter level), then scale by climate conversion factor
  group_by(Species, Region, Climate_parameter, Organismal_parameter, Intensity)%>%
  summarise(Organismal_expected2096=mean(Organismal_expected2096))%>%
  ungroup()%>%
  mutate(Organismal_parameter=factor(Organismal_parameter, levels=c("Phenology", "Swimming speed", "Survival", "Feeding", "Size", "Development", "Growth rate", "PLD", "Habitat detection")))


#Final Organismal_expected2096 calculation equivalent to the following

#Effect size = (Difference in organismal parameter)/(Control organismal parameter level) =Proportion change

#Effect size standardized by climatic range studied = (Effect size)/(difference in climate variable between control and treatment, e.g., degree C difference) = e.g., Effect size / degree C change

# Organismal_expected2096 = Climate standardized effect size * expected change in climate parameter by 2096 = Effect size / degree C change * Expected degree C change = final expected proportion change
```

```{r}
ptemp<-ggplot(filter(dsum, Region=="Temperate East Pacific")%>%droplevels(), aes(x=Organismal_expected2096, y=Organismal_parameter, color=Climate_parameter, shape=Intensity))+
  geom_blank(aes(y=Organismal_parameter))+
  geom_point(aes(y=as.numeric(Organismal_parameter)+(as.numeric(as.factor(Climate_parameter))-2)/(8/(7/9))), size=2, alpha=0.8, fill="white", stroke=1.5)+
  geom_vline(xintercept=0)+
  facet_wrap(~Species, ncol=1)+
  scale_color_colorblind(name="Climate parameter", guide="none")+
  scale_shape_manual(values=c(21,16))+
  scale_x_continuous(limits=c(min(dsum$Organismal_expected2096), max(dsum$Organismal_expected2096)), labels=seq(-1, 2.5, by=0.5), breaks=seq(-1, 2.5, by=0.5))+
  xlab("Proportional change in organismal factor")+
  ylab("Organismal factor")+
  ggtitle("Temperate East Pacific")+
  theme_bw()+
  theme(panel.grid=element_blank(), legend.position=c(0.8,0.07), strip.background=element_blank(), text = element_text(size = 12), strip.text = element_text(face = "italic", size=10), plot.title = element_text(hjust=0.5), panel.spacing = unit(0, "in"), legend.background=element_rect(color="black", fill="white"))

ptrop<-ggplot(filter(dsum, Region=="Tropical Indian/Pacific"), aes(x=Organismal_expected2096, y=Organismal_parameter, color=Climate_parameter, shape=Intensity))+
  geom_blank(aes(y=Organismal_parameter))+
  geom_point(aes(y=as.numeric(Organismal_parameter)+(as.numeric(as.factor(Climate_parameter))-2)/8), fill="white", size=2, alpha=0.8, stroke=1.5)+
  geom_vline(xintercept=0)+
  facet_wrap(~Species, ncol = 1)+
  scale_color_colorblind(name="Climate factor")+
  scale_shape_manual(values=c(21,16), guide="none")+
  scale_x_continuous(limits=c(min(dsum$Organismal_expected2096), max(dsum$Organismal_expected2096)), labels=seq(-1, 2.5, by=0.5), breaks=seq(-1, 2.5, by=0.5))+
  xlab("Proportional change in organismal factor")+
  ggtitle("Tropical Indian/Pacific")+
  ylab("")+
  theme_bw()+
  theme(panel.grid=element_blank(), strip.background=element_blank(), legend.position=c(0.77,0.1), legend.background=element_rect(color="black", fill="white"), text = element_text(size = 12), strip.text = element_text(face = "italic", size=10), plot.title = element_text(hjust=0.5), panel.spacing = unit(0, "in"))

p<-ptemp|ptrop

ggsave(filename="Quantitative figure.tiff", p, width=8.5, height=10, units="in", dpi=400, device="tiff")
```

